=== CodeInPolish/ProjetSD/output/result.dtd
<!ELEMENT path (actor+, movie+)>
<!ATTLIST path 
cost CDATA #REQUIRED
nbMovies CDATA #REQUIRED>

<!ELEMENT actor (#PCDATA)>

<!ELEMENT movie EMPTY>
<!ATTLIST movie 
name CDATA #REQUIRED
year CDATA #IMPLIED>

=== CodeInPolish/ProjetSD/output/output.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE path SYSTEM "result.dtd">
<path cost="149" nbMovies="3">
<actor>Macaulay Culkin</actor>
<movie name="My Girl" year="1991"/>
<actor>Jody Wilson(I)</actor>
<movie name="Big Trouble" year="2002"/>
<actor>Lars Arentz-Hansen</actor>
<movie name="Beach, The" year="2000"/>
<actor>Guillaume Canet</actor>
</path>

=== CodeInPolish/ProjetSD/output.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE path SYSTEM "result.dtd">
<path cost="247" nbMovies="3">
	<actor>Macaulay Culkin</actor>
	<movie name="Good Son, The" year="1993">Good Son, The</movie>
	<actor>Gerry Becker</actor>
	<movie name="Cell, The" year="2000">Cell, The</movie>
	<actor>Leonardo DiCaprio</actor>
	<movie name="Celebrity" year="1998">Celebrity</movie>
	<actor>Guillaume Canet</actor>
</path>

=== CodeInPolish/ProjetSD/output/output2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE path SYSTEM "result.dtd">
<path cost="91" nbMovies="4">
<actor>Macaulay Culkin</actor>
<movie name="Good Son, The" year="1993">Good Son, The</movie>
<actor>Elijah Wood</actor>
<movie name="Eternal Sunshine of the Spotless Mind" year="2004">Eternal Sunshine of the Spotless Mind</movie>
<actor>Tom Wilkinson(I)</actor>
<movie name="Ghost and the Darkness, The" year="1996">Ghost and the Darkness, The</movie>
<actor>Alex Ferns</actor>
<movie name="Joyeux Noël" year="2005">Joyeux Noël</movie>
<actor>Guillaume Canet</actor>
</path>
